// Types for the tolet-vision pipeline's exported preview dataset
// (data/spotted-boards-dataset.json, generated by
// tools/tolet-vision/src/exportBoardsForPreview.js from
// panoramaRegistry.js's deduped board registry).
//
// Deliberately separate from lib/spotted-boards.ts's SpottedBoard type —
// that one is the live, Supabase-backed, user-submitted feature; this one
// is a static, local-only, automated-detection preview. Different data
// source, different trust model, must never be confused as the same
// dataset.
export type PreviewBoard = {
  id: string;
  key: string;
  phone: string | null;
  bhk: string | null;
  rent: string | null;
  propertyName: string | null;
  latitude: number;
  longitude: number;
  imagePath: string;
  score: number;
  ocrConfidence: number;
  observationCount: number;
  sources: string[];
  cluster: string;
  locality: string;
  localityKey: string;
  firstSeenAt: string;
  // Present only on entries added by exportGoogleComparisonForPreview.js —
  // the Ola detection pipeline's own entries predate this field and are
  // implicitly provider "ola". Lets the preview UI tell a real Ola
  // detection apart from a Google Tiles comparison capture at the same
  // physical location, since both can now coexist in one dataset.
  provider?: "ola" | "google";
  googleSessionId?: string;
  olaBoardKey?: string | null;
  olaPhone?: string | null;
  hasDetection?: boolean;
};

export type PreviewMapConfig = {
  centerLat: number;
  centerLon: number;
  zoom: number;
  width: number;
  height: number;
  fileName: string;
  boardCount: number;
};

export type PreviewDataset = {
  generatedAt: string;
  boardCount: number;
  maps: Record<string, PreviewMapConfig | null>;
  boards: PreviewBoard[];
};

export const CLUSTER_LABELS: Record<string, string> = {
  all: "All areas",
  koramangala: "Koramangala",
  indiranagar: "Indiranagar",
  whitefield: "Whitefield",
  other: "Other",
  "google-comparison": "Google Tiles comparison",
};

export function groupByCluster(boards: PreviewBoard[]): Record<string, PreviewBoard[]> {
  const groups: Record<string, PreviewBoard[]> = {};
  for (const board of boards) {
    (groups[board.cluster] ??= []).push(board);
  }
  return groups;
}
